#!/bin/sh

if [ $# != 1 -a $# != 2 ];
then
	echo $#
	echo "Argument error! use './sim [Component Name]', './sim [Component Name] [Testbench Name]' or './sim clean'"
	exit -1
fi
if [ $1 == "clean" ];
then
	if [ ! -d work ];
	then
		mkdir work
	fi
	cd work		
	rm -rf ./*
else
	if [ $# == 2 ];
	then
		cd ..
		cp asm_example/$2.asm asm_example/test.asm
		./assembler.sh asm_example/test.asm
		cd dlx_sim
	fi
	cd work
	make -f ../Makefiles/$1.make
fi
